spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    location: banner.txt
  devtools:
    restart:
      exclude: static/**,public/**,templates/**
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true